### ISSUE TITLE
About the apk package dataset application

### ISSUE THREAD

**Issue by ayjin-dev** [yinghuali/AIApp#1]
Hello administrator,

 I apologize in advance for my disturbance. 

 I am here to request to use this dataset for deep learning application research. I would be grateful if you could be allowed to do so. Thank you!

This is my email: ayjin@stu.ujn.edu.cn

**Comment by yinghuali** [comment]
Yes, you can use these AI apps to do research.

**Comment by ayjin-dev** [comment]
Oh thanks!! so could you please share this dataset?

**Comment by yinghuali** [comment]
The datasets are also in this project. The link is https://github.com/yinghuali/AIApp/blob/main/data/ai_apps.csv
